// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingApp.Data;

#nullable disable

namespace TicketingApp.Migrations
{
    [DbContext(typeof(TicketContext))]
    [Migration("20250718100000_AddConversationId")]
    partial class AddConversationId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketingApp.Models.Ticket", b =>
            {
                b.Property<int>("TicketId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"), 82L);

                b.Property<string>("Corpo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("GraphMessageId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ConversationId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTime>("DataApertura")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DataUltimaModifica")
                    .HasColumnType("datetime2");

                b.Property<string>("GestoreEmail")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("MittenteEmail")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Oggetto")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)");

                b.Property<string>("Stato")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("TicketId");

                b.HasIndex("GraphMessageId")
                    .IsUnique();

                b.HasIndex("ConversationId")
                    .IsUnique();

                b.ToTable("Ticket", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}